language: python - "3.5"

addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.5

install:
    - pip install --user -r requirements.txt
    - pip install --user travis-sphinx

script:
    - travis-sphinx --source=. build

after_success:
    - travis-sphinx deploy
